version: '3.3'

services:
  ros_tester:
    container_name: ros_tester
    image: automatedtestingservice/ros-tester
    volumes:
      - './host:/host'
      - './student:/student'
      - './tester:/tester'

